list and tuples are ordered

dictionaires: key value pair

In [ ]:
a = (1,2,3,4,5)
b = (6,7,8,9)

a = a + b
a

(1, 2, 3, 4, 5, 6, 7, 8, 9)

In [ ]:
dict = {"name": "nikkhil", "age": 36, "country": "india", "name":"garg"}
print(dict)


{'name': 'garg', 'age': 36, 'country': 'india'}


In [ ]:
t1 = (1, 2, 3)
t2 = (4, 5, 6)


In [ ]:
id(t1)

132089376932992

In [ ]:
t1 = t1 + t2
id(t1)

132089376863136

In [ ]:
num = [1,2,3,4,5,6,7,8,9,10]

#add 2 to each number and then print result

i = 0 #iterator

while(i < len(num)):#defining the condition is based on iterator variable
    print(num[i]+2) #define your operation  by connecting the iterator with the sequence
    i += 1 #increment

3
4
5
6
7
8
9
10
11
12


In [ ]:
for i in num:
    print(i+2)

3
4
5
6
7
8
9
10
11
12


In [ ]:
for i in num:
    print(i+2,end=" ")

3 4 5 6 7 8 9 10 11 12 

Conditional Statements

In [ ]:
x = 15
y = 18

#first condition will always start from if
if x > y:
  print("x is greater than y") #if above condition is true
elif x < y:
  print("x is less than y")
else:
    print("y is equal to x")
#else will always come in last

x is less than y


In [ ]:
# If else statement
a=18

if(a<10):
    print("Less than 10")
elif(10<=a<=25):
    print("In between 10 and 25")
else:
    print("Greater than 25")

In [ ]:
# If else statement
a=18

if(a<10):
    print("Less than 10")
else:
    print("Greater than or equal to 10")

Greater than or equal to 10


develop a conditional block

marks =

if your marks are less than 40 then I want you to print a message Fail

between 40 and 60, Average

between 60 - 80, excellent

between 80-95, outstanding

above 95, You will be admitted in a Delhi University College

In [ ]:
marks = 60

#first condition starts with if keyword

if(marks<40):
    print("Fail")
elif(40<=marks<=60):
    print("Average")
elif(60<marks<=80):
    print("Excellent")
elif(80<marks<=95):
    print("Outstanding")
else:
    print("You will be admitted in a Delhi University College")

In [ ]:
a = 8
print("okay") if a < 10 else print("bye")

okay


In [ ]:
#and
a = 200
b = 33
c = 350
if a > b and c > a:
  print("Both conditions are True")

In [ ]:
#or
a = 200
b = 33
c = 500
if a > b or a > c:
  print("At least one of the conditions is True")

In [ ]:
#Nested If
#You can have if statements inside if statements, this is called nested if statements.

x = 12

#outer and inner block combination
#inner block will activate only if outer block condition is satisfied

if x < 10:#outer block/condition/case one
    print("below ten,")#outer block operation
    if x > 5:#inner block
        print("and also above 5")
    else:
        print("but not above 5")
elif 10<=x<20: #case 2, outer block no. 2
    print("Above ten")
    if x > 15:
        print("number above 15")
    elif x==15:
        print("the number is equal to 15")
    else:
        print("below 15")


Above ten
below 15


text File handling in python

In [ ]:
z = open("worktodo.txt")
#the file is opened in read mode by default

In [ ]:
z = open("/content/worktodo.txt")
#the file is opened in read mode by default

In [ ]:
print(z.read()) #read the entire content of text file

Hello, my name is Nikkhil garg. I am your instructor and mentor for data science and machine learning course. Hope you are having a wonderful day.

Its a pleasure to be with you and become part of your learning environment. Anything you wish to ask and talk, do let me know.

I am all there.


In [ ]:
z.close()

In [ ]:
z = open("worktodo.txt")
#the file is opened in read mode by default

In [ ]:

print(z.readline())

Hello, my name is Nikkhil garg. I am your instructor and mentor for data science and machine learning course. Hope you are having a wonderful day.



In [ ]:
z.close()

In [ ]:
z = open("worktodo.txt")
#the file is opened in read mode by default

In [ ]:
print(z.readline())
print(z.readline())
print(z.readline())

Hello, my name is Nikkhil garg. I am your instructor and mentor for data science and machine learning course. Hope you are having a wonderful day.



Its a pleasure to be with you and become part of your learning environment. Anything you wish to ask and talk, do let me know.



In [ ]:
print(z.readline())

In [ ]:
z.close()

pen function: Filename (pwd), mode mention the complete address of the file

Read : "r" #default

Write: "w"

Append: "a"

Create: "x"

text mode and the binary (images)

In [ ]:
z = open("worktodo.txt", "a") #open file in append mode
#the file is opened in read mode by default

z.write("\nI hope all of you are practicing well")

z.close()

z = open("worktodo.txt")

print(z.read())

z.close()

Hello, my name is Nikkhil garg. I am your instructor and mentor for data science and machine learning course. Hope you are having a wonderful day.

Its a pleasure to be with you and become part of your learning environment. Anything you wish to ask and talk, do let me know.

I am all there.
I hope all of you are practicing well
I hope all of you are practicing well


In [ ]:
z = open("worktodo.txt", "w") #open file in append mode
#the file is opened in read mode by default

z.write("\nI wish you all the best for your future")

z.close()

z = open("worktodo.txt")

print(z.read())

z.close()


I wish you all the best for your future


In [ ]:
z = open("worktodo.txt",'a')
z.write("\ni love india ")
z.close() # this is wrong which i corrected later
z = open("worktodo.txt",'r')
print(z.read())


I wish you all the best for your future
i love india 
i love india 
i love india 
i love india 
i love india 


In [ ]:
f = open("worktodo.txt")

for x in f.readlines():
    print(x)



I wish you all the best for your future

i love india 

i love india 

i love india 

i love india 

i love india 


list comprehension

In [ ]:
#numbers = [1,2,3,4,5,6,7,8]

def get_even(numbers):
  for num in numbers:
    if num % 2 == 0:
      print(num)

get_even([1, 2, 3, 4, 5, 6])

2
4
6


In [ ]:
#print the even numbers from a sequence, condition number % 2 == 0
def get_even(numbers):
  even_nums = [num for num in numbers if num % 2==0] #list comrephension
  return even_nums

get_even([1, 2, 3, 4, 5, 6])


[2, 4, 6]

In [ ]:
#print the even numbers from a sequence, condition number % 2 == 0
def get_even(numbers):
  print([num for num in numbers if num % 2==0]) #list comrephension

get_even([1, 2, 3, 4, 5, 6])


[2, 4, 6]


In [ ]:
f = open("worktodo.txt")
content = f.read()
for i in content:
    print(i)



I
 
w
i
s
h
 
y
o
u
 
a
l
l
 
t
h
e
 
b
e
s
t
 
f
o
r
 
y
o
u
r
 
f
u
t
u
r
e


i
 
l
o
v
e
 
i
n
d
i
a
 


i
 
l
o
v
e
 
i
n
d
i
a
 


i
 
l
o
v
e
 
i
n
d
i
a
 


i
 
l
o
v
e
 
i
n
d
i
a
 


i
 
l
o
v
e
 
i
n
d
i
a
 


In [ ]:
f = open("worktodo.txt")
content = f.read().split()   # split into words
for word in content:
    print(word, end=" ")     # print words on one line with spaces
f.close()

I wish you all the best for your future i love india i love india i love india i love india i love india 

In [ ]:
f = open("worktodo.txt")

for line in f.readlines():
    print(line.strip())

f.close()



I wish you all the best for your future
i love india
i love india
i love india
i love india
i love india


Errors & Exceptions

**Type error, value error, syntax error, not implemented, out of index, key error, indentation error, attribute error, file not found error, variable not defined, name error, module not found error**

In [ ]:
x

NameError: name 'x' is not defined

In [ ]:
import xghk

ModuleNotFoundError: No module named 'xghk'

Common Built-in Exceptions:

ZeroDivisionError: Occurs when dividing by zero.

NameError: When a local or global name is not found.

TypeError: Passing an object of an inappropriate type.

IndexError: When an index is not found in a sequence.

KeyError: When a dictionary key is not found.

FileNotFoundError: When a file or directory is requested but doesn't exist.

Handling Exceptions with try and except:

Python uses try and except blocks to catch and handle exceptions.

In [ ]:
3/0

ZeroDivisionError: division by zero

In [ ]:
print(Tax)

NameError: name 'Tax' is not defined

len(nikkhil)

In [ ]:
len("nikkhil")

7

In [ ]:
len(5)

TypeError: object of type 'int' has no len()

In [ ]:
lst = [1,2,3]
lst[3]

IndexError: list index out of range

In [ ]:
dic = {"name": "nikhil"}
dic["age"]

KeyError: 'age'

In [ ]:
int("xyz")

ValueError: invalid literal for int() with base 10: 'xyz'

In [ ]:
"hello".append("age")

AttributeError: 'str' object has no attribute 'append'

In [ ]:
try:
    # Code block where exception can occur
except ExceptionType:
    # Code to execute if there is an ExceptionType exception

In [ ]:
try:
  result = 20 /0
except ZeroDivisionError:
  print("Attempt to divide by zero will not work")

  #ZeroDivisionError: division by zero

Attempt to divide by zero will not work


In [ ]:
try:
    result = 20 / 0
except ZeroDivisionError:
    while True:
        pass   # infinite loop
#illogical bug

KeyboardInterrupt: 

In [ ]:
try:
  print(nikhil)
except NameError:
  print("Variable of such name doesnt exist")

Variable of such name doesnt exist


In [ ]:
try:
  len(5)
except TypeError:
  print('wrong data type with len method')

wrong data type with len method


In [ ]:
try:
  print(lste)
  print(len(5))
except NameError:
  print("Variable of such name doesnt exist")
except TypeError:
  print("'wrong data type with len method'")

Variable of such name doesnt exist


In [ ]:
#nested try and except

try:
    file = open("data.txt", "r")
    try:
        content = file.read()
        print(content[1000])  # Might raise IndexError
    except IndexError:
        print("Inner except: Tried to access content beyond range")
    finally:
        file.close()
        print("Inner finally: File closed")
except FileNotFoundError:
    print("Outer except: File does not exist")


OOPs

In [ ]:
class Employee:
    name = "John"
    age = 26

#declare object using class employee
h1 = Employee() #object is the instance of the class

#print features
print(h1.name)
print(h1.age)

John
26


In [ ]:
class customer:
    def identity(self,name, age):
        print("I am a customer " + name)
        print("The age is ", age)

cust = customer() #declaration of object

cust.identity("NIkhil", 36)
cust.identity("Poonam", 32)
cust.identity("Sarvesh", 42)

I am a customer NIkhil
The age is  36
I am a customer Poonam
The age is  32
I am a customer Sarvesh
The age is  42


In [ ]:
class Customer:
    def set_details(self, new_name, new_age):
        self.name = new_name#declaring name attribute
        self.age = new_age#declaring age attribute

cust = Customer()#declaration of an object

cust.set_details("Nikhil", 36)
print(cust.name, cust.age)

cust.set_details("Poonam", 32)
print(cust.name, cust.age)

cust.set_details("Sarvesh", 42)
print(cust.name, cust.age)

Nikhil 36
Poonam 32
Sarvesh 42


In [ ]:
class Employee:
    def __init__(self, name, age):
        self.name = name
        self.age = age

e1 = Employee("Sam", 36) #init is implicitly called
e2 = Employee("Rakesh", 42)
e3 = Employee("Aditya", 24)

print(e1.name, e1.age)
print(e2.name, e2.age)
print(e3.name, e3.age)

Sam 36
Rakesh 42
Aditya 24


In [ ]:
class Employee:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def Print(self):#no parameters
        print("My name is ", self.name)
        print("My age is ", self.age)

p1 = Employee("NIkhil", 36).Print()
p2 = Employee("Prerna", 30)
p3 = Employee("Sriram", 26)
p4 = Employee("Mangesh", 18)
p5 = Employee("Shukla", 32)
p6 = Employee("Hari", 15)

p1.Print()
p2.Print()
p3.Print()
p4.Print()
p5.Print()
p6.Print()


My name is  NIkhil
My age is  36


In [ ]:
class Customer:
    def __init__(self, name, balance=0):
        self.name = name
        self.balance = balance

cust = Customer("Brain Lara")

print(cust.name, cust.balance)

Brain Lara 0


In [ ]:
class Person:
    def __init__(self, fname, lname):
        self.firstname = fname
        self.lastname = lname

    def printname(self):
        print(self.firstname, self.lastname)

x = Person("John", "Doe")

x.printname()

John Doe


In [ ]:
class child(Person):
    pass

In [ ]:
y = Person("John", "Doe")

y.printname()

John Doe


In [ ]:
class child(Person):
    def __init__
#inheritance is lost if init constructor is used in child class

SyntaxError: expected '(' (ipython-input-3063416455.py, line 2)

In [ ]:
class Student(Person):#fname and lname
    def __init__(self, fname, lname, year):#year is the additional attribute
        Person.__init__(self, fname, lname)#additional call to the parent class

In [ ]:
#using the super function
class Student(Person):
    def __init__(self, fname, lname, year):
        super().__init__(fname, lname)#will come from the parent class

In [ ]:
#using the super function
class Student(Person):
    def __init__(self, fname, lname, year):
        super().__init__(fname, lname)#will come from the parent class
        self.graduationyear = year#additional attribute

x = Student("Mike", "Olsen", 2019)
x.printname()#printname method i coming from the parent class

Mike Olsen


In [ ]:
#using the super function
class Student(Person):
    def __init__(self, fname, lname, year):
        super().__init__(fname, lname)
        self.graduationyear = year
    def Print(self):
        print("Welcome", self.firstname, self.lastname, "to the class of", self.graduationyear)

x = Student("Mike", "Olsen", 2022)
x.Print()


Welcome Mike Olsen to the class of 2022


In [ ]:
2 + 3

5

In [ ]:
#polymorphism #same name function used for different types
#same operator

print(len("geeks"))

len("nikkhil")
len([1,2,3])

3

In [ ]:
"nikkhil" + "garg"

'nikkhilgarg'

In [ ]:
tup1 = (1,2,3)
tup2 = (6,4,5)

tup1 + tup2

(1, 2, 3, 6, 4, 5)

In [ ]:
type(tup1)

tuple

In [ ]:
#del

In [ ]:
x = 5
y = 0
print("x:", x)
print("y:", y)
result = x / y

x: 5
y: 0


ZeroDivisionError: division by zero

In [ ]:
import pdb

x = 10
y = 0
pdb.set_trace()  # Execution pauses here
result = x / y

--Return--
None
> /tmp/ipython-input-51947323.py(5)<cell line: 0>()
      2 
      3 x = 10
      4 y = 0
----> 5 pdb.set_trace()  # Execution pauses here
      6 result = x / y

ipdb> q


In [ ]:
import logging
logging.basicConfig(level=logging.DEBUG)

x = 5
logging.debug(f"x value: {x}")

In [ ]:
x = 23.23
type(x)

float

---

# **Debugging Techniques in Python**

## **1. Introduction to Debugging**

**What is Debugging?**
Debugging is the process of finding and fixing errors (bugs) in your program so it runs as intended.

**Why Debugging is Important?**

* Saves time in the long run by catching problems early.
* Prevents unexpected crashes or incorrect outputs.
* Improves code quality and maintainability.

**Types of Errors in Python**

1. **Syntax Errors** – Mistakes in the structure of the code (e.g., missing colon `:`).
2. **Runtime Errors (Exceptions)** – Errors that occur when the program is running (e.g., dividing by zero).
3. **Logical Errors** – Program runs but produces incorrect results due to flawed logic.

---

## **2. Basic Debugging Techniques**

### **a) Reading Error Messages**

* Python’s error messages give the **type of error**, **line number**, and a short **description**.
* Example:

```python
print("Hello"
```

**Output:**

```
SyntaxError: unexpected EOF while parsing
```

* Always start debugging by reading the error message carefully.

---

### **b) Using `print()` Statements**

* One of the simplest ways to debug is by printing variable values.

```python
x = 5
y = 0
print("x:", x)
print("y:", y)
result = x / y  # This will cause ZeroDivisionError
```

* Use this to trace the **flow of execution** and **check variable values**.

**Tips for print debugging:**

* Add clear labels when printing.
* Remove or comment out debug prints before finalizing the code.

---

### **c) Checking Variable Types with `type()`**

Sometimes a bug is caused by unexpected data types.

```python
a = "10"
b = 5
print(type(a), type(b))  # Shows str and int
```

* Fix by converting:

```python
a = int(a)
```

---

## **3. Using the Built-in `pdb` Debugger**

Python comes with the **`pdb` (Python Debugger)** module.

**How to Use:**

1. Import `pdb`
2. Insert `pdb.set_trace()` where you want to pause execution.

```python
import pdb

x = 10
y = 0
pdb.set_trace()  # Execution pauses here
result = x / y
```

**When paused, you can:**

* `n` → go to next line
* `c` → continue execution
* `p variable` → print variable value
* `q` → quit debugger

---

## **4. Using an IDE Debugger (PyCharm, VS Code, Thonny)**

Most IDEs have **graphical debuggers** where you can:

* Set **breakpoints** (pause execution at a line).
* Step through code line by line.
* Watch variables in real-time.
* Evaluate expressions without modifying the code.

Example in **VS Code**:

1. Click on the left margin to set a breakpoint.
2. Run in debug mode (`F5`).
3. Use controls for step-in (`F11`), step-out (`Shift+F11`), and step-over (`F10`).

---

## **5. Handling Exceptions with `try-except`**

* Use exception handling to **catch** and **diagnose** errors without stopping the program.

```python
try:
    num = int(input("Enter a number: "))
    print(10 / num)
except ZeroDivisionError:
    print("You can't divide by zero!")
except ValueError:
    print("Invalid input. Please enter a number.")
```

* Good for **user input validation** and preventing program crashes.

---

## **6. Debugging Logic Errors**

Logic errors don’t show error messages, but output is wrong.
**Approach:**

* Break the code into smaller parts and test each separately.
* Use test cases with **expected results**.
* Compare actual output with expected output.

Example:

```python
def add_numbers(a, b):
    return a - b  # Wrong logic
print(add_numbers(5, 3))  # Expected 8, got 2
```

---

## **7. Using Logging for Debugging**

`logging` is better than print statements for larger programs.

```python
import logging
logging.basicConfig(level=logging.DEBUG)

x = 5
logging.debug(f"x value: {x}")
```

Advantages over print:

* Can control verbosity.
* Can write logs to a file.
* Easier to remove or disable in production.

---

## **8. Common Beginner Mistakes and Fixes**

| **Mistake**                | **Why it Happens**            | **Fix**                             |
| -------------------------- | ----------------------------- | ----------------------------------- |
| Not reading error messages | Skipping the most useful info | Carefully read the full traceback   |
| Mixing data types          | String + int errors           | Convert types with `int()`, `str()` |
| Infinite loops             | Wrong loop condition          | Add debug prints or breakpoints     |
| Off-by-one errors          | Wrong index or range          | Print loop counters to verify       |

---

## **9. Practice Exercise**

Here’s a buggy code snippet — try to debug it:

```python
def calculate_area(length, width):
    area = length * widht
    return area

print(calculate_area(5, 3))
```

**Steps to debug:**

1. Run and read error message.
2. Fix typo: `widht` → `width`.
3. Test again.

---

## **10. Summary**

* **Start with reading error messages**.
* **Use print or logging** for quick checks.
* **Use pdb or IDE debuggers** for step-by-step execution.
* **Handle exceptions** to avoid crashes.
* **Test logic** with known inputs and expected outputs.

---



** Dictionary Comprehension**

{key_expression: value_expression for item in iterable if condition}

In [ ]:
squares = {}
for num in range(5):
    squares[num] = num ** 2
print(squares)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


In [ ]:
squares = {num: num ** 2 for num in range(5)}
print(squares)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


In [ ]:
even_squares = {num: num ** 2 for num in range(10) if num % 2 == 0}
print(even_squares)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


In [ ]:
usd_prices = {"apple": 2, "banana": 1, "cherry": 3}
inr_prices = {item: price * 83 for item, price in usd_prices.items()}
print(inr_prices)

{'apple': 166, 'banana': 83, 'cherry': 249}


**counting characters in a string**

In [ ]:
text = "hello"
text.count('l')

2

In [ ]:
text = "hello"
char_count = {char: text.count(char) for char in text}
print(char_count)
# Output: {'h': 1, 'e': 1, 'l': 2, 'o': 1}

{'h': 1, 'e': 1, 'l': 2, 'o': 1}


FIlter dictionary data

In [ ]:
marks = {"A": 85, "B": 42, "C": 77, "D": 90}
passed = {name: score for name, score in marks.items() if score >= 50}
print(passed)

{'A': 85, 'C': 77, 'D': 90}


ROW COLUMN

Arrays: numbers/numeric data

no name of columns/variables/features

no row labels

NumPy -- Scipy

Tables: any data types

col names are essential

row labels are optional

Pandas

**NUMPY**

In [ ]:
import numpy as np #context manager

#create an array
x = np.array([1,2,3]) #list of numbers
print(x)

[1 2 3]


In [ ]:
type(x)

numpy.ndarray

Dimensions in arrays

single row array: 1 D

otherwise: 2 D

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #list of lists
print(a)
#array with 4 rows and 3 columns

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
a.ndim

2

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(a)
#4 rows and 4 columns
a.ndim

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


2

In [ ]:
a.shape

(4, 4)

In [ ]:
a.size

16

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
#hypthetical: array of 0s

np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#array of ones
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#arange fn in python generates sequence of numbers

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
#concatenation #joining
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a)
print()
print(b)

np.concatenate((a, b))

[1 2 3 4]

[5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#both arrays have same shape and same dimension
x = np.array([[1,2], [3,4], [7,8]])#array 0f 3 rows and 2 columns

y = np.array([[5,6],[9,10],[11,12]])

print(x)
print()
print(y)


[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]
 [11 12]]


In [ ]:
np.concatenate((x, y),axis=0) #axis 0 is default -- row concatenation


array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10],
       [11, 12]])

axis in arrays

axis = 0, vertical axis -- top to bottom

axis = 1, horizontal axis -- left to right

In [ ]:
#arrays with same dimensions but with diff shape

x = np.array([[1,2], [3,4], [7,8]])#array 0f 3 rows and 2 columns

y = np.array([[5,6],[9,10]])

print(x)
print()
print(y)


[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]]


In [ ]:
#arrays with same dimensions but with diff shape

x = np.array([[1,2], [3,4], [7,8]])#array 0f 3 rows and 2 columns

y = np.array([[5,6]]) #casting

print(x)
print()
print(y)


[[1 2]
 [3 4]
 [7 8]]

[[5 6]]


In [ ]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [7, 8],
       [5, 6]])

In [ ]:
x = np.array([[1,2], [3,4], [7,8]])#array 0f 3 rows and 2 columns

y = np.array([[5,6,7],[9,10,11]])

print(x)
print()
print(y)


[[1 2]
 [3 4]
 [7 8]]

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
np.concatenate((x, y))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
#both arrays have same shape and same dimension
x = np.array([[1,2], [3,4], [7,8]])#array 0f 3 rows and 2 columns

y = np.array([[5,6],[9,10],[11,12]])

print(x)
print()
print(y)


[[1 2]
 [3 4]
 [7 8]]

[[ 5  6]
 [ 9 10]
 [11 12]]


In [ ]:
np.concatenate((x, y), axis = 1) #coluumn concatenation

array([[ 1,  2,  5,  6],
       [ 3,  4,  9, 10],
       [ 7,  8, 11, 12]])

In [ ]:
x = np.array([[1,2], [3,4], [7,8]])#array 0f 3 rows and 2 columns

y = np.array([[5,6,7],[9,10,11],[12,13,14]])

print(x)
print()
print(y)

[[1 2]
 [3 4]
 [7 8]]

[[ 5  6  7]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
np.concatenate((x, y), axis = 1) #coluumn concatenation

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  9, 10, 11],
       [ 7,  8, 12, 13, 14]])

**Split of an array**

In [ ]:
import numpy as np
#splitting
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
newarr[1]

array([3, 4])

In [ ]:
import numpy as np
#splitting
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
import numpy as np
#splitting
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 10)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [ ]:
arr = np.array([[1,2], [3,4],[5,6], [7,8], [9,10], [11,12]])
arr
#2 D array with 6 x 2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
newarr = np.array_split(arr, 6)
print(newarr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [ ]:
newarr = np.array_split(arr, 10)
print(newarr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]


In [ ]:
#equal division
newarr = np.split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#equal division
newarr = np.split(arr,6)
print(newarr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [ ]:
#equal division
newarr = np.split(arr,10)
print(newarr)

ValueError: array split does not result in an equal division

In [ ]:
#split a 2darray into three 2d arrays along rows/accross columns
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:

newarr = np.array_split(arr, 3, axis = 0) #default -- row split
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
newarr = np.array_split(arr, 3, axis = 1) #column split
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
newarr = np.array_split(arr, 4, axis = 1) #column split
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int64)]


In [ ]:
newarr = np.split(arr, 3, axis = 1) #column split
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#sorting of an array
arr = np.array([2,1,5,3,7,4,6,8])
ar = np.sort(arr)
print(ar)
#ascending order
ar

[1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
ar[::1] #start, end, step/jump

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
ar[::2] #start, end, step/jump

array([1, 3, 5, 7])

In [ ]:
ar[::-1] #start, end, step/jump

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
ar[::-2] #start, end, step/jump

array([8, 6, 4, 2])

**Reshaping of an array**

In [ ]:
#reshaping of an array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
a.reshape(-1,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.reshape(- 1,4)

ValueError: cannot reshape array of size 6 into shape (4)

**Arithmetic operations**

In [ ]:
import numpy as np
#simple operators
data = np.array([1,2])

ones = np.ones(2, dtype=int)

a = np.array([3,4])

print(data)
print()
print(ones)
print(a)

[1 2]

[1 1]
[3 4]


In [ ]:
data + ones + a

array([5, 7])

In [ ]:
data * ones * a

array([3, 8])

In [ ]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[5,6], [7,8]])

print(a1, a2, sep="\n")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
a1 + a2

array([[ 6,  8],
       [10, 12]])

In [ ]:
a1 / a2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a1 * a2

array([[ 5, 12],
       [21, 32]])

In [ ]:
#matrix multiplication as per maths
np.dot(a1, a2)

array([[19, 22],
       [43, 50]])

In [ ]:
#2d arrays with different shapes --  Exceptional scenario
a1 = np.array([[1,2], [3,4,]])

a2 = np.array([[5,6]]) #casting

print(a1)
print()
print(a2)

[[1 2]
 [3 4]]

[[5 6]]


In [ ]:
a1 + a2

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
#2d array with different sizes
data = np.array([[1,2], [3,4,]])

datas = np.array([[5,6], [7,8], [8,9]])

print(datas)
print()
print(data)

[[5 6]
 [7 8]
 [8 9]]

[[1 2]
 [3 4]]


In [ ]:
data + datas

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a[a < 5]

array([1, 2, 3, 4])

In [ ]:
print(a[(a > 2) & (a < 11)])
#and operator all conditions must be satisfied

[ 3  4  5  6  7  8  9 10]


In [ ]:
print(a[(a > 2) | (a < 11)])
#atleast one condition shall be satisfied

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Indexing & Slicing**

In [ ]:
dataone  = np.array([[1,2], [3,4,], [5,6]])
dataone

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
dataone[0] #o index -- 1st row

array([1, 2])

In [ ]:
dataone[2]

array([5, 6])

In [ ]:
dataone[0,1] #row, col

np.int64(2)

In [ ]:
dataone[0:2,1] #row,col

array([2, 4])

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
a[1:3,0:2] #row,col

array([[ 5,  6],
       [ 9, 10]])

**Tables/Dataframes**

In [ ]:
import pandas as pd

titanic = pd.read_csv("titanic.csv")
titanic # top 5 and bottom 5 rows

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex    age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.00      0      0   24160  211.3375       B5        S    2   
1       male   0.92      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.00      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.00      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.00      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...    ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.50      1      0    2665   14.4542      NaN        C  NaN   
1305  female    NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.50      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.00      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.00      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [ ]:
titanic.head() #top 5 rows

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

     age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.00      0      0   24160  211.3375       B5        S    2    NaN   
1   0.92      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.00      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [ ]:
titanic.tail() #bottom 5 rows

pclass  survived                       name     sex   age  sibsp  parch  \
1304       3         0       Zabour, Miss. Hileni  female  14.5      1      0   
1305       3         0      Zabour, Miss. Thamine  female   NaN      1      0   
1306       3         0  Zakarian, Mr. Mapriededer    male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin    male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo    male  29.0      0      0   

      ticket     fare cabin embarked boat   body home.dest  
1304    2665  14.4542   NaN        C  NaN  328.0       NaN  
1305    2665  14.4542   NaN        C  NaN    NaN       NaN  
1306    2656   7.2250   NaN        C  NaN  304.0       NaN  
1307    2670   7.2250   NaN        C  NaN    NaN       NaN  
1308  315082   7.8750   NaN        S  NaN    NaN       NaN

In [ ]:
titanic.shape

(1309, 14)

In [ ]:
titanic["pclass"].unique()

array([1, 2, 3])

In [ ]:
titanic["pclass"].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [ ]:
titanic["survived"].unique()

array([1, 0])

In [ ]:
titanic["sex"].unique()

array(['female', 'male'], dtype=object)

In [ ]:
titanic["sex"].value_counts()

sex
male      843
female    466
Name: count, dtype: int64

In [ ]:
#summary of dataframe
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [ ]:
#to check missing values
titanic.isna().any()

pclass       False
survived     False
name         False
sex          False
age           True
sibsp        False
parch        False
ticket       False
fare          True
cabin         True
embarked      True
boat          True
body          True
home.dest     True
dtype: bool

In [ ]:
titanic.isna().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [ ]:
titanic.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

     age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.00      0      0   24160  211.3375       B5        S    2    NaN   
1   0.92      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.00      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [ ]:
age_sex = titanic[["name","sex","age"]]
age_sex.head()

name     sex    age
0                    Allen, Miss. Elisabeth Walton  female  29.00
1                   Allison, Master. Hudson Trevor    male   0.92
2                     Allison, Miss. Helen Loraine  female   2.00
3             Allison, Mr. Hudson Joshua Creighton    male  30.00
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00