In [2]:
import numpy as np

In [3]:
v1 = np.array([ 
    [63,90,77],
    [33,99,877],
    [80,660,56] ] )
print("v1.ndim : ",v1.ndim)
print("v1.shape : ",v1.shape)
v1_split = np.array_split(v1,3,axis=0) # split along rows.
v1_split

v1.ndim :  2
v1.shape :  (3, 3)


[array([[63, 90, 77]]), array([[ 33,  99, 877]]), array([[ 80, 660,  56]])]

In [4]:
v2 = np.array([ 
    [63,90,77],
    [33,99,877],
    [80,660,56] ] )
print("v2.ndim : ",v2.ndim)
print("v2.shape : ",v2.shape)
v2_split = np.array_split(v2,4,axis=1) # split along columns.
v2_split

v2.ndim :  2
v2.shape :  (3, 3)


[array([[63],
        [33],
        [80]]),
 array([[ 90],
        [ 99],
        [660]]),
 array([[ 77],
        [877],
        [ 56]]),
 array([], shape=(3, 0), dtype=int64)]

In [5]:
v3 = np.array([67,89,77,66,12,56,456,31])
v3_srt = np.sort(v3) # ascending default sort order
v3_srt

array([ 12,  31,  56,  66,  67,  77,  89, 456])

In [6]:
v3_srt[::-1] # reverse order sort - start index : end index : step -1 indicates reversing

array([456,  89,  77,  67,  66,  56,  31,  12])

In [7]:
v3_srt[::-2] # reverse order sort - start index : end index : step -2 indicates reversing
# - sign indicates right to left.

array([456,  77,  66,  31])

In [8]:
# Reshaping
v4_arr = np.arange(10)
v4_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(v4_arr.shape)
print(v4_arr.ndim)

(10,)
1


In [10]:
v5_arr=v4_arr.reshape(-1,2) # -1 indicates that python calculate the number of rows
v5_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
print(v5_arr.shape)
print(v5_arr.ndim)

(5, 2)
2


In [12]:
v6_arr=v4_arr.reshape(2,5) # reshape to 2 rows and 5 columns
v6_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
print(v6_arr.shape)
print(v6_arr.ndim)

(2, 5)
2


In [14]:
# Arithmetic operations in numpy happen in element wise
arthm1 = np.array([
         [10, 11],
         [231, 300]])

arthm2 = np.ones(4).reshape(-1,2) * 3
print(arthm1, arthm2, sep="\n")

[[ 10  11]
 [231 300]]
[[3. 3.]
 [3. 3.]]


In [15]:
arthm2 + arthm1

array([[ 13.,  14.],
       [234., 303.]])

In [16]:
arthm2 * arthm1

array([[ 30.,  33.],
       [693., 900.]])

In [17]:
arthm2 / arthm1

array([[0.3       , 0.27272727],
       [0.01298701, 0.01      ]])

In [18]:
arthm1 - arthm2

array([[  7.,   8.],
       [228., 297.]])

In [19]:
# Matrix Multiplication  used in high -end nueral network modeling
np.dot(arthm1,arthm2)

array([[  63.,   63.],
       [1593., 1593.]])

In [20]:
arthm3 = np.array([
         [10, 50],
         [60, 70]])

arthm4 = np.array([
         [2, 3],
         [4, 5]])

print(arthm3, arthm4, sep="\n")

[[10 50]
 [60 70]]
[[2 3]
 [4 5]]


In [21]:
print("Arithmetic Product : ",arthm3 * arthm4, sep="\n")

Arithmetic Product : 
[[ 20 150]
 [240 350]]


In [22]:
print("Matrix Product : ",np.dot(arthm3, arthm4), sep="\n")

Matrix Product : 
[[220 280]
 [400 530]]


In [23]:
# add one row array (1,n) to another differrent shaped array (x,n) with same column dimension. Exclusive scenario
arthm5 = np.array([
         [10, 50,63],
         [60, 70,63], 
         [600, 700,63]])

arthm6 = np.array([
         [2, 3,7]])

print(arthm5.shape, arthm6.shape, sep="\n")
print(arthm5, arthm6, sep="\n")

print(arthm5+arthm6, sep="\n")

(3, 3)
(1, 3)
[[ 10  50  63]
 [ 60  70  63]
 [600 700  63]]
[[2 3 7]]
[[ 12  53  70]
 [ 62  73  70]
 [602 703  70]]


In [24]:
#filter array elements
arthm6 = np.array([
         [10, 50,63],
         [60, 70,63], 
         [600, 700,63]])

print(arthm6[arthm6 > 100])
print(arthm6[(arthm6 > 10) & (arthm6 < 500)])
print(arthm6[(arthm6 < 200) | (arthm6 < 50)])

[600 700]
[50 63 60 70 63 63]
[10 50 63 60 70 63 63]


In [25]:
# Indexing Slicing
arthm7 = np.array([
         [10, 50,65],
         [60, 70,63], 
         [600, 700,64]])

# element is extracted and a row array ius created.
print(arthm7[1]) # get row index 1
print(arthm7[1,2]) # get row index 1 and col index 32
print(arthm7[:2]) # get  2 rows as end index is 2
print(arthm7[0:2,1]) # get values from 2 rows and column as index 1
print(arthm7[1:2,2]) 

[60 70 63]
63
[[10 50 65]
 [60 70 63]]
[50 70]
[63]


In [27]:
# Indexing Slicing
arthm8 = np.array([
         [10, 50,65,78],
         [60, 70,63,99], 
         [600, 700,64,45],
         [56, 11,88,31]])

print(arthm8[0:3,1:3])
print(arthm8[2:3,2:3])

[[ 50  65]
 [ 70  63]
 [700  64]]
[[64]]
