In [1]:
import numpy as np

In [10]:
v1 = np.array([ 
    [63,90,77],
    [33,99,877],
    [80,660,56] ] )
print("v1.ndim : ",v1.ndim)
print("v1.shape : ",v1.shape)
v1_split = np.array_split(v1,3,axis=0) # split along rows.
v1_split

v1.ndim :  2
v1.shape :  (3, 3)


[array([[63, 90, 77]]), array([[ 33,  99, 877]]), array([[ 80, 660,  56]])]

In [11]:
v2 = np.array([ 
    [63,90,77],
    [33,99,877],
    [80,660,56] ] )
print("v2.ndim : ",v2.ndim)
print("v2.shape : ",v2.shape)
v2_split = np.array_split(v2,4,axis=1) # split along columns.
v2_split

v2.ndim :  2
v2.shape :  (3, 3)


[array([[63],
        [33],
        [80]]),
 array([[ 90],
        [ 99],
        [660]]),
 array([[ 77],
        [877],
        [ 56]]),
 array([], shape=(3, 0), dtype=int64)]

In [ ]:
v3 = np.array([67,89,77,66,12,56,456,31])
v3_srt = np.sort(v3) # ascending default sort order
v3_srt

array([ 12,  31,  56,  66,  67,  77,  89, 456])

In [ ]:
v3_srt[::-1] # reverse order sort - start index : end index : step -1 indicates reversing

array([456,  89,  77,  67,  66,  56,  31,  12])

In [18]:
v3_srt[::-2] # reverse order sort - start index : end index : step -2 indicates reversing
# - sign indicates right to left.

array([456,  77,  66,  31])

In [42]:
# Reshaping
v4_arr = np.arange(10)
v4_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
print(v4_arr.shape)
print(v4_arr.ndim)

(10,)
1


In [44]:
v5_arr=v4_arr.reshape(-1,2) # -1 indicates that python calculate the number of rows
v5_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
print(v5_arr.shape)
print(v5_arr.ndim)

(5, 2)
2


In [48]:
v6_arr=v4_arr.reshape(2,5) # reshape to 2 rows and 5 columns
v6_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
print(v6_arr.shape)
print(v6_arr.ndim)

(2, 5)
2


In [62]:
# Arithmetic operations in numpy happen in element wise
arthm1 = np.array([
         [10, 11],
         [231, 300]])

arthm2 = np.ones(4).reshape(-1,2) * 3
print(arthm1, arthm2, sep="\n")

[[ 10  11]
 [231 300]]
[[3. 3.]
 [3. 3.]]


In [63]:
arthm2 + arthm1

array([[ 13.,  14.],
       [234., 303.]])

In [65]:
arthm2 * arthm1

array([[ 30.,  33.],
       [693., 900.]])

In [66]:
arthm2 / arthm1

array([[0.3       , 0.27272727],
       [0.01298701, 0.01      ]])

In [67]:
arthm1 - arthm2

array([[  7.,   8.],
       [228., 297.]])

In [ ]:
# Matrix Multiplication  used in high -end nueral network modeling
np.dot(arthm1,arthm2)

array([[  63.,   63.],
       [1593., 1593.]])

In [71]:
arthm3 = np.array([
         [10, 50],
         [60, 70]])

arthm4 = np.array([
         [2, 3],
         [4, 5]])

print(arthm3, arthm4, sep="\n")

[[10 50]
 [60 70]]
[[2 3]
 [4 5]]


In [74]:
print("Arithmetic Product : ",arthm3 * arthm4, sep="\n")

Arithmetic Product : 
[[ 20 150]
 [240 350]]


In [75]:
print("Matrix Product : ",np.dot(arthm3, arthm4), sep="\n")

Matrix Product : 
[[220 280]
 [400 530]]
