In [1]:
import numpy as np

In [ ]:
a = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]
    ]) #list of lists
print(a)
print(a.ndim) # more than 1 row means , the dimension is 2. Measures the dimensions.
print(a.shape)
print(type(a))
print(a.size) # total elements in an array


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)
<class 'numpy.ndarray'>
12


In [14]:
np.linspace(1,100,5)  #generates linear data with equal spacing

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [20]:
x1 = np.array([[1,2], [3,4], [7,8]])#array 0f 3 rows and 2 columns

y1 = np.array([[5,6],[9,10]])

print("Concatenate arrays -> ",(x1,y1))

np.concatenate((x1,y1))

Concatenate arrays ->  (array([[1, 2],
       [3, 4],
       [7, 8]]), array([[ 5,  6],
       [ 9, 10]]))


array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 5,  6],
       [ 9, 10]])

In [21]:
x2 = np.array([[1,2,5], [3,4,78], [7,8,8]])#array 0f 3 rows and 2 columns

y2 = np.array([[5,6],[9,10]])

print("Concatenate arrays -> ",(x2,y2))

np.concatenate((x2,y2))

Concatenate arrays ->  (array([[ 1,  2,  5],
       [ 3,  4, 78],
       [ 7,  8,  8]]), array([[ 5,  6],
       [ 9, 10]]))


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [26]:
x3 = np.array([  [3,4,78], [7,8,8] ])

y3 = np.array([96,55,99])


print("y3 dimension -> ",y3,y3.ndim)
print("Concatenate arrays -> ",(x3,y3))

np.concatenate((x3,y3))

y3 dimension ->  [96 55 99] 1
Concatenate arrays ->  (array([[ 3,  4, 78],
       [ 7,  8,  8]]), array([96, 55, 99]))


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# Ensure arrays are in same dimension when concatenation
x4 = np.array([  [3,4,78], [7,8,8] ])

y4 = np.array(  [  [96,55,99]   ]  ) # casting change dimension from 1 D to 2D

print("y4 dimension -> ",y4,y4.ndim)

print("Concatenate arrays -> ",(x4,y4))

np.concatenate((x4,y4), axis=0) #no of cols should match. axis=0 is default

y4 dimension ->  [[96 55 99]] 2
Concatenate arrays ->  (array([[ 3,  4, 78],
       [ 7,  8,  8]]), array([[96, 55, 99]]))


array([[ 3,  4, 78],
       [ 7,  8,  8],
       [96, 55, 99]])

When working with arrays there is always a concept of axis.
axis = 0 -> refers to vertical axis (top to bottom)
axis = 1 -> refers to horizontal axis (left to right)
Ensure datastructure while concatenation.

In [ ]:
# axis=0 row concatenation will take place.
# Ensure arrays are in same dimension when concatenation
x5 = np.array([  [3,4,78], [7,8,8] ])

y5 = np.array(  [ [96,55,99] , [70,8,80]   ]    ) 

print("x5  -> \n",x5)
print("y5  -> \n",y5)

print("concatenate on axis = 0 : \n",np.concatenate((x5,y5), axis=0) ) # row concatenation
print("concatenate on axis = 1 : \n",np.concatenate((x5,y5), axis=1) ) # column concatenation

x5  -> 
 [[ 3  4 78]
 [ 7  8  8]]
y5  -> 
 [[96 55 99]
 [70  8 80]]
concatenate on axis = 0 : 
 [[ 3  4 78]
 [ 7  8  8]
 [96 55 99]
 [70  8 80]]
concatenate on axis = 1 : 
 [[ 3  4 78 96 55 99]
 [ 7  8  8 70  8 80]]


In [44]:
# axis=0 row concatenation will take place.
# Ensure arrays are in same dimension when concatenation
x6 = np.array([  [3,4], 
                 [7,8] ])

y6 = np.array(  [ [96,55,99] , 
                  [70,8,80]   ]    ) 

print("x5  -> \n",x6)
print("y5  -> \n",y6)

print("concatenate on axis = 1 : \n",np.concatenate((x6,y6), axis=1) ) # column concatenation

x5  -> 
 [[3 4]
 [7 8]]
y5  -> 
 [[96 55 99]
 [70  8 80]]
concatenate on axis = 1 : 
 [[ 3  4 96 55 99]
 [ 7  8 70  8 80]]


In [53]:
x7 = np.array( [63,90,77,33,99,877,660,56] )
x7_split = np.array_split(x7,7)
x7_split

[array([63, 90]),
 array([77]),
 array([33]),
 array([99]),
 array([877]),
 array([660]),
 array([56])]

In [ ]:
x8 = np.array( [63,90,77,33,99,877,660,56] )
x8_split = np.array_split(x8,10)
x8_split # 2 empty arrays are created. Doesnt work in the concept in equal divisions.

[array([63]),
 array([90]),
 array([77]),
 array([33]),
 array([99]),
 array([877]),
 array([660]),
 array([56]),
 array([], dtype=int64),
 array([], dtype=int64)]

In [61]:
# split arrays from multidimension. #original array dimension will be maintained.
x9 = np.array( [ [63,90],[77,33],[99,877],[660,56] ] )
x9_split = np.array_split(x9,10)
x9_split

[array([[63, 90]]),
 array([[77, 33]]),
 array([[ 99, 877]]),
 array([[660,  56]]),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64),
 array([], shape=(0, 2), dtype=int64)]

In [ ]:
# split arrays only with equal dimension. #original array dimension will be maintained.
x9 = np.array( [ [63,90],[77,33],[99,877],[660,56] ] )
x9_split = np.array_split(x9,10)
x9_split