In [63]:
# python debugger module.
import pdb

In [46]:
class Person:
    # constructor
    def __init__(self, fname, lname):
        self.firstname = fname
        self.lastname = lname

    def print(self):
        print(self.firstname, self.lastname)

x = Person("John", "Doe")

x.print()

John Doe


In [39]:
class child(Person):
    pass

In [40]:
#inheritance is lost if init constructor is used in child class
class child(Person):
   def __init__():
      print("initialized")

In [41]:
class Student(Person):#fname and lname
    def __init__(self, fname, lname, year):#year is the additional attribute
        Person.__init__(self, fname, lname)#additional call to the parent class

In [42]:
std1 = Student("jack","russ",2015)
std1.print()

jack russ


In [ ]:
class StudentV1(Person):#fname and lname
    def __init__(self, fname, lname, year):#year is the additional attribute
        super().__init__(fname, lname)#additional call to the parent class. #for super just put arguments
        self.grad_year = year

    #overwrite the one in parent class
    def print(self):
        print("Welcome", self.firstname, self.lastname, "to the class of", self.grad_year)    

In [45]:
std1 = StudentV1("jack","russ",2015)
std1.print()

Welcome jack russ to the class of 2015


In [ ]:
# Polymorphism - + operator is always concatenating
4+6

10

In [49]:
# Polymorphism - + operator is always concatenating
"jack"+"jill"

'jackjill'

In [50]:
tuple1 = (1,2,3)
tuple2 = (4,5,5)
tuple1 + tuple2

(1, 2, 3, 4, 5, 5)

In [51]:
len("joke")

4

In [52]:
len(tuple2)

3

In [53]:
len([4,5,5])

3

In [ ]:
tuple1 + "tuple2" # differrent data type cannot be concatenated.

TypeError: can only concatenate tuple (not "str") to tuple

In [ ]:
# type is to let know the type of data type 
type(tuple2)

tuple

In [61]:
d=19
dv = 0
print(f"Values : {d},{dv}")
print(d/dv)

Values : 19,0


ZeroDivisionError: division by zero

In [62]:
dr = "10"
v =9
print(type(dr), type(v))

<class 'str'> <class 'int'>


**Python Debugger Inputs When paused, you can:**

* `n` → go to next line
* `c` → continue execution
* `p variable` → print variable value
* `q` → quit debugger

In [72]:
d=19
dv = 0
pdb.set_trace()
print(f"Values : {d},{dv}")
print(d/dv)

--Return--
None
> c:\users\user\appdata\local\temp\ipykernel_24296\2466969691.py(3)<module>()



In [74]:
d=19
dv = 0
print(f"Values : {d},{dv}")
print(d/dv)

Values : 19,0


ZeroDivisionError: division by zero

In [78]:
try :
    your_num = int(input("Enter number : "))
    print(f"100 / your_num = {100 / your_num}")
except ZeroDivisionError as zde:
    print(zde)
except ValueError as vlerror:
    print(vlerror)

division by zero


In [81]:
geog_loc = 564646565.8976555433897898798798879
type(geog_loc)

float

In [82]:
geog_loc = "564646565.8976555433897898798798879"
type(geog_loc)

str

In [91]:
# dictionary regular for-loop in traditional way
square_vals = {}
for num in range(6): #get 6 numbers starting from 0
    square_vals[num] = num**2

square_vals

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [94]:
# dictionary comprehension
#square_vals_dict_cmpr = { key : value  (expression : for item in iterable if condition) }
square_vals_dict_cmpr = { num : num**2 for num in range(6)  }
square_vals_dict_cmpr

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [95]:
# list comprehension
square_vals_list_cmpr = [num**2 for num in range(6)  ]
square_vals_list_cmpr

[0, 1, 4, 9, 16, 25]

In [97]:
# dictionary comprehension
#square_vals_dict_cmpr = { key : value  (expression : for item in iterable if condition) }
odd_square_vals_dict_cmpr = { num : num**2 for num in range(15) if num % 2 != 0  }
odd_square_vals_dict_cmpr

{1: 1, 3: 9, 5: 25, 7: 49, 9: 81, 11: 121, 13: 169}

In [99]:
usd_fruit_prices = {"apple": 5, "banana": 7, "cherry": 9}
# create dictionary from existing dictionary values.
inr_fruit_prices = { item : 87.60 * price for item, price in usd_fruit_prices.items()}
inr_fruit_prices

{'apple': 438.0, 'banana': 613.1999999999999, 'cherry': 788.4}

In [105]:
text_str1 = "Hello How are you doing ?"
text_str1.count("?")

1

In [106]:
text_str1 = "Hello How are you doing ?"
character_count = {char : str(text_str1).count(char)   for char in text_str1}
print(character_count)

{'H': 2, 'e': 2, 'l': 2, 'o': 4, ' ': 5, 'w': 1, 'a': 1, 'r': 1, 'y': 1, 'u': 1, 'd': 1, 'i': 1, 'n': 1, 'g': 1, '?': 1}


In [111]:
std_marks = {"Raj": 85, "Gopi": 42, "Sharath": 77, "Ram": 93}
std_pssed_grades = { name : "passed"  for name, score in std_marks.items() if score >=50 }
std_pssed_grades

{'Raj': 'passed', 'Sharath': 'passed', 'Ram': 'passed'}

In [112]:
std_marks = {"Raj": 85, "Gopi": 42, "Sharath": 77, "Ram": 93}
std_pssed_scores = { name : score  for name, score in std_marks.items() if score >=50 }
std_pssed_scores

{'Raj': 85, 'Sharath': 77, 'Ram': 93}

In [126]:
import numpy as np # np_lib is a context manager

my_even_num_list = [304,506,1006,346]
print(f"my_even_num_list -> {my_even_num_list}")
print(f"type of my_even_num_list -> {type(my_even_num_list)}")


my_even_num_np_array = np.array(my_even_num_list)
print(f"my_even_num_np_array -> {my_even_num_np_array}")
print(f"type of my_even_num_np_array -> {type(my_even_num_np_array)}")
print(f"Shape of my_even_num_np_array -> {my_even_num_np_array.shape}")
print(f"Dimesnion of my_even_num_np_array -> {my_even_num_np_array.ndim}")


my_even_num_list -> [304, 506, 1006, 346]
type of my_even_num_list -> <class 'list'>
my_even_num_np_array -> [ 304  506 1006  346]
type of my_even_num_np_array -> <class 'numpy.ndarray'>
Shape of my_even_num_np_array -> (4,)
Dimesnion of my_even_num_np_array -> 1


In [132]:
#multidimension arrays
my_even_num_list_2D = [[304,506],[1006,346],[568,890],[552,666],[660,662],[880,890]]
print("List - SubList : ",my_even_num_list_2D)

my_even_num_np_array_2D = np.array(my_even_num_list_2D)
print(f"\n my_even_num_np_array_2D ->\n {my_even_num_np_array_2D}")
print(f"\n type of my_even_num_np_array_2D ->\n {type(my_even_num_np_array_2D)}")
print(f"\n Shape of my_even_num_np_array_2D -> \n{my_even_num_np_array_2D.shape}")
print(f"\n Dimesnion of my_even_num_np_array_2D ->\n {my_even_num_np_array_2D.ndim}")

List - SubList :  [[304, 506], [1006, 346], [568, 890], [552, 666], [660, 662], [880, 890]]

 my_even_num_np_array_2D ->
 [[ 304  506]
 [1006  346]
 [ 568  890]
 [ 552  666]
 [ 660  662]
 [ 880  890]]

 type of my_even_num_np_array_2D ->
 <class 'numpy.ndarray'>

 Shape of my_even_num_np_array_2D -> 
(6, 2)

 Dimesnion of my_even_num_np_array_2D ->
 2


In [133]:
my_even_num_np_array_2D_1 = np.array([ [4,6,7,9] ,  [40,60,70,90] , [400,600,700,900]               ])
print(f"\n my_even_num_np_array_2D_1 ->\n {my_even_num_np_array_2D_1}")
print(f"\n type of my_even_num_np_array_2D_1 ->\n {type(my_even_num_np_array_2D_1)}")
print(f"\n Shape of my_even_num_np_array_2D_1 -> \n{my_even_num_np_array_2D_1.shape}")
print(f"\n Dimesnion of my_even_num_np_array_2D_1 ->\n {my_even_num_np_array_2D_1.ndim}")


 my_even_num_np_array_2D_1 ->
 [[  4   6   7   9]
 [ 40  60  70  90]
 [400 600 700 900]]

 type of my_even_num_np_array_2D_1 ->
 <class 'numpy.ndarray'>

 Shape of my_even_num_np_array_2D_1 -> 
(3, 4)

 Dimesnion of my_even_num_np_array_2D_1 ->
 2


In [134]:
#hypothetical arrays
np.zeros(4)

array([0., 0., 0., 0.])

In [139]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [141]:
np.ones(4)

array([1., 1., 1., 1.])

In [142]:
np.ones([4,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.ones([4,2]).shape # count rows and cols

In [144]:
np.arange(15) # generate sequence of nmbers as an n-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [145]:
np.arange(6,15)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [150]:
seq1 = np.arange(6,25,2) # step by 2
print(seq1)
print(seq1.ndim)

[ 6  8 10 12 14 16 18 20 22 24]
1


In [ ]:
np.linspace(1,50) # all generated numbers are equidistant from each other.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [154]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [156]:
np.linspace(1,2,5) # generate 5 numbers only

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [161]:
np.linspace(1,999,3)

array([  1., 500., 999.])